version: "3"


services:

  my-home-pihole:
    image: ianstorm/my-home-pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 80:80
    restart: unless-stopped
